'\" t
.\"     Title: sss_groupdel
.\"    Author: The SSSD upstream - http://fedorahosted.org/sssd
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/24/2010
.\"    Manual: SSSD Manual pages
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSS_GROUPDEL" "8" "05/24/2010" "SSSD" "SSSD Manual pages"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sss_groupdel \- create a new group
.SH "SYNOPSIS"
.HP \w'\fBsss_groupdel\fR\ 'u
\fBsss_groupdel\fR [\fIoptions\fR] \fIGROUP\fR
.SH "DESCRIPTION"
.PP

\fBsss_groupdel\fR
deletes a group identified by its name
\fIGROUP\fR
from the system\&.
.SH "OPTIONS"
.PP
\fB\-h\fR,\fB\-\-help\fR
.RS 4
Display help message and exit\&.
.RE
.SH "SEE ALSO"
.PP

\fBsss_groupadd\fR(8),
\fBsss_groupmod\fR(8),
\fBsss_groupshow\fR(8),
\fBsss_useradd\fR(8),
\fBsss_userdel\fR(8),
\fBsss_usermod\fR(8)\&.
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \- http://fedorahosted\&.org/sssd\fR
