'\" t
.\"     Title: sssd-ipa
.\"    Author: The SSSD upstream - http://fedorahosted.org/sssd
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/08/2010
.\"    Manual: File Formats and Conventions
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-IPA" "5" "10/08/2010" "SSSD" "File Formats and Conventions"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-ipa \- the configuration file for SSSD
.SH "DESCRIPTION"
.PP
This manual page describes the configuration of the IPA provider for
\fBsssd\fR(8)\&. For a detailed syntax reference, refer to the
\(lqFILE FORMAT\(rq
section of the
\fBsssd.conf\fR(5)
manual page\&.
.PP
The IPA provider is a back end used to connect to an IPA server\&. (Refer to the freeipa\&.org web site for information about IPA servers\&.) This provider requires that the machine be joined to the IPA domain; configuration is almost entirely self\-discovered and obtained directly from the server\&.
.PP
The IPA provider accepts the same options used by the
\fBsssd-ldap\fR(5)
identity provider and the
\fBsssd-krb5\fR(5)
authentication provider\&. However, it is neither necessary nor recommended to set these options\&.
.SH "CONFIGURATION OPTIONS"
.PP
Refer to the section
\(lqDOMAIN SECTIONS\(rq
of the
\fBsssd.conf\fR(5)
manual page for details on the configuration of an SSSD domain\&.
.PP
ipa_domain (string)
.RS 4
Specifies the name of the IPA domain\&. This is optional\&. If not provided, the configuration domain name is used\&.
.RE
.PP
ipa_server (string)
.RS 4
The list of IP addresses or hostnames of the IPA servers to which SSSD should connect in the order of preference\&. For more information on failover and server redundancy, see the
\(lqFAILOVER\(rq
section\&. This is optional if autodiscovery is enabled\&. For more information on service discovery, refer to the the
\(lqSERVICE DISCOVERY\(rq
section\&.
.RE
.PP
ipa_hostname (string)
.RS 4
Optional\&. May be set on machines where the hostname(5) does not reflect the fully qualified name used in the IPA domain to identify this host\&.
.RE
.PP
ipa_dyndns_update (boolean)
.RS 4
Optional\&. This option tells SSSD to automatically update the DNS server built into FreeIPA v2 with the IP address of this client\&.
.sp
Default: false
.RE
.PP
ipa_dyndns_iface (string)
.RS 4
Optional\&. Applicable only when ipa_dyndns_update is true\&. Choose the interface whose IP address should be used for dynamic DNS updates\&.
.sp
Default: Use the IP address of the IPA LDAP connection
.RE
.PP
krb5_validate (boolean)
.RS 4
Verify with the help of krb5_keytab that the TGT obtained has not been spoofed\&.
.sp
Default: true
.sp
Note that this default differs from the traditional Kerberos provider back end\&.
.RE
.SH "FAILOVER"
.PP
The failover feature allows back ends to automatically switch to a different server if the primary server fails\&.
.SS "Failover Syntax"
.PP
The list of servers is given as a comma\-separated list; any number of spaces is allowed around the comma\&. The servers are listed in order of preference\&. The list can contain any number of servers\&.
.SS "The Failover Mechanism"
.PP
The failover mechanism distinguishes between a machine and a service\&. The back end first tries to resolve the hostname of a given machine; if this resolution attempt fails, the machine is considered offline\&. No further attempts are made to connect to this machine for any other service\&. If the resolution attempt succeeds, the back end tries to connect to a service on this machine\&. If the service connection attempt fails, then only this particular service is considered offline and the back end automatically switches over to the next service\&. The machine is still considered online and might still be tried for another service\&.
.PP
Further connection attempts are made to machines or services marked as offline after a specified period of time; this is currently hard coded to 30 seconds\&.
.PP
If there are no more machines to try, the back end as a whole switches to offline mode, and then attempts to reconnect every 30 seconds\&.
.SH "SERVICE DISCOVERY"
.PP
The service discovery feature allows back ends to automatically find the appropriate servers to connect to using a special DNS query\&.
.SS "Configuration"
.PP
If no servers are specified, the back end automatically uses service discovery to try to find a server\&. Optionally, the user may choose to use both fixed server addresses and service discovery by inserting a special keyword,
\(lq_srv_\(rq, in the list of servers\&. The order of preference is maintained\&. This feature is useful if, for example, the user prefers to use service discovery whenever possible, and fall back to a specific server when no servers can be discovered using DNS\&.
.SS "The domain name"
.PP
The name of the SSSD domain is used as the domain part of the service discovery DNS query\&.
.SS "See Also"
.PP
For more information on the service discovery mechanism, refer to RFC 2782\&.
.SH "EXAMPLE"
.PP
The following example assumes that SSSD is correctly configured and example\&.com is one of the domains in the
\fI[sssd]\fR
section\&. This examples shows only the ipa provider\-specific options\&.
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
    [domain/example\&.com]
    id_provider = ipa
    ipa_server = ipaserver\&.example\&.com
    ipa_hostname = myhost\&.example\&.com
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP

\fBsssd.conf\fR(5),
\fBsssd-ldap\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd\fR(8)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \- http://fedorahosted\&.org/sssd\fR
