'\" t
.\"     Title: sssd-ldap
.\"    Author: The SSSD upstream - http://fedorahosted.org/sssd
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/18/2010
.\"    Manual: File Formats and Conventions
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-LDAP" "5" "06/18/2010" "SSSD" "File Formats and Conventions"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-ldap \- the configuration file for SSSD
.SH "DESCRIPTION"
.PP
This manual page describes the configuration of LDAP domains for
\fBsssd\fR(8)\&. Refer to the
\(lqFILE FORMAT\(rq
section of the
\fBsssd.conf\fR(5)
manual page for detailed syntax information\&.
.PP
You can configure SSSD to use more than one LDAP domain\&.
.PP
If you want to authenticate against an LDAP server then TLS/SSL is required\&.
\fBsssd\fR
\fIdoes not\fR
support authentication over an unencrypted channel\&. If the LDAP server is used only as an identify provider, an encrypted channel is not needed\&.
.SH "CONFIGURATION OPTIONS"
.PP
All of the common configuration options that apply to SSSD domains also apply to LDAP domains\&. Refer to the
\(lqDOMAIN SECTIONS\(rq
section of the
\fBsssd.conf\fR(5)
manual page for full details\&.
.PP
ldap_uri (string)
.RS 4
Specifies the list of URIs of the LDAP servers to which SSSD should connect in the order of preference\&. Refer to the
\(lqFAILOVER\(rq
section for more information on failover and server redundancy\&. If not specified, service discovery is enabled\&. For more information, refer to the
\(lqSERVICE DISCOVERY\(rq
section\&.
.RE
.PP
ldap_search_base (string)
.RS 4
The default base DN to use for performing LDAP user operations\&.
.RE
.PP
ldap_schema (string)
.RS 4
Specifies the Schema Type in use on the target LDAP server\&. Depending on the selected schema, the default attribute names retrieved from the servers may vary\&. The way that some attributes are handled may also differ\&. Two schema types are currently supported: rfc2307 rfc2307bis The main difference between these two schema types is how group memberships are recorded in the server\&. With rfc2307, group members are listed by name in the
\fImemberUid\fR
attribute\&. With rfc2307bis, group members are listed by DN and stored in the
\fImember\fR
attribute\&.
.sp
Default: rfc2307
.RE
.PP
ldap_default_bind_dn (string)
.RS 4
The default bind DN to use for performing LDAP operations\&.
.RE
.PP
ldap_default_authtok_type (string)
.RS 4
The type of the authentication token of the default bind DN\&. The only currently supported value is "password"\&.
.RE
.PP
ldap_default_authtok (string)
.RS 4
The authentication token of the default bind DN\&. Only clear text passwords are currently supported\&.
.RE
.PP
ldap_user_search_base (string)
.RS 4
An optional base DN to restrict user searches to a specific subtree\&.
.sp
Default: the value of
\fIldap_search_base\fR
.RE
.PP
ldap_user_object_class (string)
.RS 4
The object class of a user entry in LDAP\&.
.sp
Default: posixAccount
.RE
.PP
ldap_user_name (string)
.RS 4
The LDAP attribute that corresponds to the user\'s login name\&.
.sp
Default: uid
.RE
.PP
ldap_user_uid_number (string)
.RS 4
The LDAP attribute that corresponds to the user\'s id\&.
.sp
Default: uidNumber
.RE
.PP
ldap_user_gid_number (string)
.RS 4
The LDAP attribute that corresponds to the user\'s primary group id\&.
.sp
Default: gidNumber
.RE
.PP
ldap_user_gecos (string)
.RS 4
The LDAP attribute that corresponds to the user\'s gecos field\&.
.sp
Default: gecos
.RE
.PP
ldap_user_home_directory (string)
.RS 4
The LDAP attribute that contains the name of the user\'s home directory\&.
.sp
Default: homeDirectory
.RE
.PP
ldap_user_shell (string)
.RS 4
The LDAP attribute that contains the path to the user\'s default shell\&.
.sp
Default: loginShell
.RE
.PP
ldap_user_uuid (string)
.RS 4
The LDAP attribute that contains the UUID/GUID of an LDAP user object\&.
.sp
Default: nsUniqueId
.RE
.PP
ldap_user_principal (string)
.RS 4
The LDAP attribute that contains the user\'s Kerberos User Principal Name (UPN)\&.
.sp
Default: krbPrincipalName
.RE
.PP
ldap_force_upper_case_realm (boolean)
.RS 4
Some directory servers, for example Active Directory, might deliver the realm part of the UPN in lower case, which might cause the authentication to fail\&. Set this option to a non\-zero value if you want to use an upper\-case realm\&.
.sp
Default: false
.RE
.PP
ldap_user_fullname (string)
.RS 4
The LDAP attribute that corresponds to the user\'s full name\&.
.sp
Default: cn
.RE
.PP
ldap_user_member_of (string)
.RS 4
The LDAP attribute that lists the user\'s group memberships\&.
.sp
Default: memberOf
.RE
.PP
ldap_group_search_base (string)
.RS 4
An optional base DN to restrict group searches to a specific subtree\&.
.sp
Default: the value of
\fIldap_search_base\fR
.RE
.PP
ldap_group_object_class (string)
.RS 4
The object class of a group entry in LDAP\&.
.sp
Default: posixGroup
.RE
.PP
ldap_group_name (string)
.RS 4
The LDAP attribute that corresponds to the group name\&.
.sp
Default: cn
.RE
.PP
ldap_group_gid_number (string)
.RS 4
The LDAP attribute that corresponds to the group\'s id\&.
.sp
Default: gidNumber
.RE
.PP
ldap_group_member (string)
.RS 4
The LDAP attribute that contains the names of the group\'s members\&.
.sp
Default: memberuid (rfc2307) / member (rfc2307bis)
.RE
.PP
ldap_group_uuid (string)
.RS 4
The LDAP attribute that contains the UUID/GUID of an LDAP group object\&.
.sp
Default: nsUniqueId
.RE
.PP
ldap_search_timeout (integer)
.RS 4
Specifies the timeout (in seconds) that ldap searches are allowed to run before they are cancelled and cached results are returned (and offline mode is entered)
.sp
Default: 5 (When enumerate = False)
.sp
Default: 30 (When enumerate = True \- this option will be forced to a minumum of 30s in this case)
.sp
Note: this option is subject to change in future versions of the SSSD\&. It will likely be replaced at some point by a series of timeouts for specific lookup types\&.
.RE
.PP
ldap_network_timeout (integer)
.RS 4
Specifies the timeout (in seconds) after which the
\fBpoll\fR(2)/\fBselect\fR(2)
following a
\fBconnect\fR(2)
returns in case of no activity\&.
.sp
Default: 5
.RE
.PP
ldap_opt_timeout (integer)
.RS 4
Specifies a timeout (in seconds) after which calls to synchronous LDAP APIs will abort if no response is received\&. Also controls the timeout when communicating with the KDC in case of SASL bind\&.
.sp
Default: 5
.RE
.PP
ldap_tls_reqcert (string)
.RS 4
Specifies what checks to perform on server certificates in a TLS session, if any\&. It can be specified as one of the following values:
.sp

\fInever\fR
= The client will not request or check any server certificate\&.
.sp

\fIallow\fR
= The server certificate is requested\&. If no certificate is provided, the session proceeds normally\&. If a bad certificate is provided, it will be ignored and the session proceeds normally\&.
.sp

\fItry\fR
= The server certificate is requested\&. If no certificate is provided, the session proceeds normally\&. If a bad certificate is provided, the session is immediately terminated\&.
.sp

\fIdemand\fR
= The server certificate is requested\&. If no certificate is provided, or a bad certificate is provided, the session is immediately terminated\&.
.sp

\fIhard\fR
= Same as
\(lqdemand\(rq
.sp
Default: hard
.RE
.PP
ldap_tls_cacert (string)
.RS 4
Specifies the file that contains certificates for all of the Certificate Authorities that
\fBsssd\fR
will recognize\&.
.sp
Default: use OpenLDAP defaults, typically in
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_tls_cacertdir (string)
.RS 4
Specifies the path of a directory that contains Certificate Authority certificates in separate individual files\&. Typically the file names need to be the hash of the certificate followed by \'\&.0\'\&. If available,
\fBcacertdir_rehash\fR
can be used to create the correct names\&.
.sp
Default: use OpenLDAP defaults, typically in
/etc/openldap/ldap\&.conf
.RE
.PP
ldap_id_use_start_tls (boolean)
.RS 4
Specifies that the id_provider connection must also use
tls
to protect the channel\&.
.sp
Default: false
.RE
.PP
ldap_sasl_mech (string)
.RS 4
Specify the SASL mechanism to use\&. Currently only GSSAPI is tested and supported\&.
.sp
Default: none
.RE
.PP
ldap_sasl_authid (string)
.RS 4
Specify the SASL authorization id to use\&. When GSSAPI is used, this represents the Kerberos principal used for authentication to the directory\&.
.sp
Default: host/machine\&.fqdn@REALM
.RE
.PP
ldap_krb5_keytab (string)
.RS 4
Specify the keytab to use when using SASL/GSSAPI\&.
.sp
Default: System keytab, normally
/etc/krb5\&.keytab
.RE
.PP
ldap_krb5_init_creds (boolean)
.RS 4
Specifies that the id_provider should init Kerberos credentials (TGT)\&. This action is performed only if SASL is used and the mechanism selected is GSSAPI\&.
.sp
Default: true
.RE
.PP
ldap_krb5_ticket_lifetime (integer)
.RS 4
Specifies the lifetime in seconds of the TGT if GSSAPI is used\&.
.sp
Default: 86400 (24 hours)
.RE
.PP
krb5_realm (string)
.RS 4
Specify the Kerberos REALM (for SASL/GSSAPI auth)\&.
.sp
Default: System defaults, see
/etc/krb5\&.conf
.RE
.PP
ldap_pwd_policy (string)
.RS 4
Select the policy to evaluate the password expiration on the client side\&. The following values are allowed:
.sp

\fInone\fR
\- No evaluation on the client side\&. This option cannot disable server\-side password policies\&.
.sp

\fIshadow\fR
\- Use
\fBshadow\fR(5)
style attributes to evaluate if the password has expired\&. Note that the current version of sssd cannot update this attribute during a password change\&.
.sp

\fImit_kerberos\fR
\- Use the attributes used by MIT Kerberos to determine if the password has expired\&. Use chpass_provider=krb5 to update these attributes when the password is changed\&.
.sp
Default: none
.RE
.PP
ldap_referrals (boolean)
.RS 4
Specifies whether automatic referral chasing should be enabled\&.
.sp
Please note that sssd only supports referral chasing when it is compiled with OpenLDAP version 2\&.4\&.13 or higher\&.
.sp
Default: true
.RE
.PP
ldap_dns_service_name (string)
.RS 4
Specifies the service name to use when service discovery is enabled\&.
.sp
Default: ldap
.RE
.PP
ldap_access_filter (string)
.RS 4
If using access_provider = ldap, this option is mandatory\&. It specifies an LDAP search filter criteria that must be met for the user to be granted access on this host\&. If access_provider = ldap and this option is not set, it will result in all users being denied access\&. Use access_provider = allow to change this default behavior\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
access_provider = ldap
ldap_access_filter = memberOf=cn=allowedusers,ou=Groups,dc=example,dc=com
                        
.fi
.if n \{\
.RE
.\}
.sp
This example means that access to this host is restricted to members of the "allowedusers" group in ldap\&.
.sp
Offline caching for this feature is limited to determining whether the user\'s last online login was granted access permission\&. If they were granted access during their last login, they will continue to be granted access while offline and vice\-versa\&.
.sp
Default: Empty
.RE
.SH "FAILOVER"
.PP
The failover feature allows back ends to automatically switch to a different server if the primary server fails\&.
.SS "Failover Syntax"
.PP
The list of servers is given as a comma\-separated list; any number of spaces is allowed around the comma\&. The servers are listed in order of preference\&. The list can contain any number of servers\&.
.SS "The Failover Mechanism"
.PP
The failover mechanism distinguishes between a machine and a service\&. The back end first tries to resolve the hostname of a given machine; if this resolution attempt fails, the machine is considered offline\&. No further attempts are made to connect to this machine for any other service\&. If the resolution attempt succeeds, the back end tries to connect to a service on this machine\&. If the service connection attempt fails, then only this particular service is considered offline and the back end automatically switches over to the next service\&. The machine is still considered online and might still be tried for another service\&.
.PP
Further connection attempts are made to machines or services marked as offline after a specified period of time; this is currently hard coded to 30 seconds\&.
.PP
If there are no more machines to try, the back end as a whole switches to offline mode, and then attempts to reconnect every 30 seconds\&.
.SH "SERVICE DISCOVERY"
.PP
The service discovery feature allows back ends to automatically find the appropriate servers to connect to using a special DNS query\&.
.SS "Configuration"
.PP
If no servers are specified, the back end automatically uses service discovery to try to find a server\&. Optionally, the user may choose to use both fixed server addresses and service discovery by inserting a special keyword,
\(lq_srv_\(rq, in the list of servers\&. The order of preference is maintained\&. This feature is useful if, for example, the user prefers to use service discovery whenever possible, and fall back to a specific server when no servers can be discovered using DNS\&.
.SS "The domain name"
.PP
The name of the SSSD domain is used as the domain part of the service discovery DNS query\&.
.SS "See Also"
.PP
For more information on the service discovery mechanism, refer to RFC 2782\&.
.SH "EXAMPLE"
.PP
The following example assumes that SSSD is correctly configured and LDAP is set to one of the domains in the
\fI[domains]\fR
section\&.
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
    [domain/LDAP]
    id_provider = ldap
    auth_provider = ldap
    ldap_uri = ldap://ldap\&.mydomain\&.org
    ldap_search_base = dc=mydomain,dc=org
    ldap_tls_reqcert = demand
    cache_credentials = true
    enumerate = true
.fi
.if n \{\
.RE
.\}
.sp
.SH "NOTES"
.PP
The descriptions of some of the configuration options in this manual page are based on the
\fBldap.conf\fR(5)
manual page from the OpenLDAP 2\&.4 distribution\&.
.SH "SEE ALSO"
.PP

\fBsssd.conf\fR(5),
\fBsssd-krb5\fR(5),
\fBsssd\fR(8)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \- http://fedorahosted\&.org/sssd\fR
