'\" t
.\"     Title: sssd-simple
.\"    Author: The SSSD upstream - http://fedorahosted.org/sssd
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 08/24/2010
.\"    Manual: File Formats and Conventions
.\"    Source: SSSD
.\"  Language: English
.\"
.TH "SSSD\-SIMPLE" "5" "08/24/2010" "SSSD" "File Formats and Conventions"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sssd-simple \- the configuration file for SSSD\'s \'simple\' access\-control provider
.SH "DESCRIPTION"
.PP
This manual page describes the configuration of the simple access\-control provider for
\fBsssd\fR(8)\&. For a detailed syntax reference, refer to the
\(lqFILE FORMAT\(rq
section of the
\fBsssd.conf\fR(5)
manual page\&.
.PP
The simple access provider grants or denies access based on an access or deny list of user names\&. Here to following rules apply:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If both lists are empty, access is granted
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If simple_allow_users is set, only users from this list are allowed access\&.
.sp
This setting supersedes the simple_deny_users list (which would be redundant)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If the simple_allow_users list is empty, users are allowed access unless they appear in the simple_deny_users list
.RE
.sp
.RE
.SH "CONFIGURATION OPTIONS"
.PP
Refer to the section
\(lqDOMAIN SECTIONS\(rq
of the
\fBsssd.conf\fR(5)
manual page for details on the configuration of an SSSD domain\&.
.PP
simple_allow_users (string)
.RS 4
Comma separated list of users who are allowed to log in\&.
.RE
.PP
simple_deny_users (string)
.RS 4
Comma separated list of users who are rejected if simple_allow_users is not set\&.
.RE
.PP
Please note that it is an configuration error if both, simple_allow_users and simple_deny_users, are defined\&.
.SH "EXAMPLE"
.PP
The following example assumes that SSSD is correctly configured and example\&.com is one of the domains in the
\fI[sssd]\fR
section\&. This examples shows only the simple access provider\-specific options\&.
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
    [domain/example\&.com]
    access_provider = simple
    simple_allow_users = user1, user2
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP

\fBsssd.conf\fR(5),
\fBsssd\fR(8)
.SH "AUTHORS"
.PP
\fBThe SSSD upstream \- http://fedorahosted\&.org/sssd\fR
